name: income-expense-budget-plan
version: 1.1.1
summary: Income Expense Budget Planner
description: "This app help to input and keep track your money related activities like income, expense, transfer money... We also help you to get month reports about your activities so that you can have an overall what did you spend and what your finance statuses. This will help to adjust your expense for a better life. We support multiple platforms as Windows, Linux, MacOS, iOS, Android. Feel free to contact my email: doanbaotrung@gmail.com for any question or comment or request. Your comment will be a big help to support me improve the software. This application is free of charge."

confinement: strict
base: core24
grade: stable

slots:
  income-expense-budget-plan: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.dbaotrung.income_expense_budget_plan # adjust accordingly to your app name and

apps:
  income-expense-budget-plan:
    command: income_expense_budget_plan
    extensions: [gnome] # gnome includes the libraries required by flutter
    #plugs:
    #  - network
    slots:
      - income-expense-budget-plan

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [ arm64 ]
    build-for: [ arm64 ]

parts:
  income-expense-budget-plan:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
   
    stage:
        - -ios/**
        - -windows/**
        - -web/**
        - -macos/**
        - -adndroid/**
        - -linux/**
        - -build/**
        - -test-data/**
        - -.dart_tool/**
        - -.idea/**
        - -ci_scripts/**
